//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary_stock_quote_alert.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassLibrary_stock_quote_alert.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ALZR11;Alianza Trust Renda Imobiliaria Fundo Investimento Imobiliario
        ///ABEV3;Ambev S.A.
        ///ARZZ3;Arezzo Indústria e Comércio S.A.
        ///AZUL4;Azul S.A.
        ///BTOW3;B2W Companhia Digital
        ///B3SA3;B3 S.A. - Brasil, Bolsa, Balcão
        ///BBDC3;Banco Bradesco S.A.
        ///BBDC4;Banco Bradesco S.A.
        ///BBAS3;Banco do Brasil S.A.
        ///BRSR6;Banco do Estado do Rio Grande do Sul S.A.
        ///BIDI4;Banco Inter S.A.
        ///BIDI3;Banco Inter S.A.
        ///SANB3;Banco Santander (Brasil) S.A.
        ///SANB11;Banco Santander (Brasil) S.A.
        ///BBPO11;BB Progressivo II Fundo de Investimen [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ativos_disponiveis_csv {
            get {
                return ResourceManager.GetString("ativos_disponiveis.csv", resourceCulture);
            }
        }
    }
}
